name: ie-bank-frontend

on:
  push:
    branches:
      - '*' # Matches all branches
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  FRONTEND_WEBAPP_DEV: makenna-fe-dev
  FRONTEND_WEBAPP_UAT: makenna-fe-uat
  FRONTEND_WEBAPP_PROD: makenna-fe-prod

jobs:
  build-dev:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: npm install and build (Dev)
        env:
          NODE_ENV: development
        run: |
          npm ci
          npm run build:dev

      - name: Upload artifact for deployment (Dev)
        uses: actions/upload-artifact@v3
        with:
          name: node-app-dev
          path: dist-dev/

  build-uat:
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: npm install and build (UAT)
        env:
          NODE_ENV: development  # Install devDependencies
        run: |
          npm ci
          NODE_ENV=uat npm run build:uat

      - name: Upload artifact for deployment (UAT)
        uses: actions/upload-artifact@v3
        with:
          name: node-app-uat
          path: dist-uat/

  build-prod:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: npm install and build (Prod)
        env:
          NODE_ENV: development  # Install devDependencies
        run: |
          npm ci
          NODE_ENV=production npm run build:prod

      - name: Upload artifact for deployment (Prod)
        uses: actions/upload-artifact@v3
        with:
          name: node-app-prod
          path: dist-prod/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-dev
          path: dist-dev/

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Dev)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: dist-dev/

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build-uat
    environment:
      name: 'UAT'
      url: ${{ steps.deploy-to-webapp-uat.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-uat
          path: dist-uat/

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (UAT)
        id: deploy-to-webapp-uat
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: dist-uat/

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build-prod
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp-prod.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-prod
          path: dist-prod/

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App (Prod)
        id: deploy-to-webapp-prod
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_PROD }}
          package: dist-prod/
