name: ie-bank-frontend

on:
  workflow_dispatch:
  pull_request:
    branches:
      - '*' # Matches all branches
  push:
    branches:
      - '*' # Matches all branches
    paths-ignore:
      - 'scripts/**'

env:
  FRONTEND_WEBAPP_DEV: makenna-fe-dev
  FRONTEND_WEBAPP_UAT: makenna-fe-uat

jobs:
  build-dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build for development
        env:
          NODE_ENV: development
        run: npm run build:dev

      - name: Verify build output
        run: ls -la dist-dev

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app-dev
          path: dist-dev/

  build-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build for UAT
        env:
          NODE_ENV: uat
        run: npm run build:uat

      - name: Verify build output
        run: ls -la dist-uat

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v3
        with:
          name: node-app-uat
          path: dist-uat/

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build-dev

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-dev

      - name: Verify downloaded files
        run: ls -la

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_DEV }}
          package: dist-dev/

  deploy-uat:
    runs-on: ubuntu-latest
    needs: build-uat

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app-uat

      - name: Verify downloaded files
        run: ls -la

      - name: Login to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.FRONTEND_WEBAPP_UAT }}
          package: dist-uat/
